### ISSUE TITLE
Open GL error 1282 with Optifine

### ISSUE THREAD

**Issue by mentalnoah** [SquidDev-CC/CC-Tweaked#1183] opened 2022-10-15 06:28 UTC
### Minecraft Version

1.19.x

### Version

1.100.10

### Details

steps to reproduce: place an advanced monitor next to an advanced computer, or place the advanced computer next to advanced monitor, it will make the monitor transparent and you will get an OpenGL error 1282 in chat, 
if you destroy the computer the problem stays until you destroy the monitor that was attached to the computer
![image](https://user-images.githubusercontent.com/61484747/195971591-cce02a1e-78d0-4894-bab4-a444598a6111.png)

it doesn't matter what side you place it on, it will cause this bug, it happens on servers(i ran it on an aternos server) running this version as well

i have other mods:
journey map 
inventory sorter 
jei
optifine
cc:tweaked

the server was running the same mods as the list (excluding optifine and jei)

logs:
[2022-10-15-5.log](https://github.com/cc-tweaked/CC-Tweaked/files/9791305/2022-10-15-5.log)

**Comment by SquidDev** [comment] 2022-10-15 07:11
I suspect this is caused by Optifine. If you can, I'd recommend removing it.

You might be able to resolve this by [switching to the VBO](https://github.com/cc-tweaked/CC-Tweaked/wiki/Monitor-renderers) backend. We should switch automatically, but I also haven't tested this behaviour on 1.19.2.

**Comment by mentalnoah** [comment] 2022-10-15 10:31
> I suspect this is caused by Optifine. If you can, I'd recommend removing it.
> 
> You might be able to resolve this by [switching to the VBO](https://github.com/cc-tweaked/CC-Tweaked/wiki/Monitor-renderers) backend. We should switch automatically, but I also haven't tested this behaviour on 1.19.2.

I tried the option of removing Optifine, Which worked, although the switching to VBO doesnt work, or at least i couldnt get it to work, which kinda sucks because my friends on the server like using optifine, we will probably have to suck it up and play without optifine. Thanks tho, for a solution.

**Comment by SquidDev** [comment] 2022-10-15 11:59
>  which kinda sucks because my friends on the server like using optifine,

You might be able to use [Oculus](https://modrinth.com/mod/oculus/) and [Rubidium](https://modrinth.com/mod/rubidium/) instead. This _should_ work with CC:T and, unlike Optifine, is open source - which means it's much easier to debug when things go wrong!

**Comment by SquidDev** [comment] 2022-10-15 12:23
Have decided I'm going to mark this as wontfix.

My instinct is that Optifine has started patching something in the `VertexBuffer` code which is incompatible with our [buffer uploading code](https://github.com/cc-tweaked/CC-Tweaked/blob/mc-1.19.x/src/main/java/dan200/computercraft/client/util/DirectVertexBuffer.java). However, I've purged memory of how to reverse-engineer Optifine, and have no wish to do it again - I'd recommend opening an issue on their issue tracker and the devs there might be able to offer some insight.

**Closed as not planned by SquidDev** 2022-10-15 12:23 UTC
Labels: bug, invalid, wontfix, area-Minecraft
