### ISSUE TITLE
NoSuchMethodError server crash

### ISSUE THREAD

**Issue by kreezxil** [SquidDev-CC/CC-Tweaked#181] opened 2019-04-20 16:26 UTC
## Useful information to include:

*   Minecraft version 1.12.2.-14.23.5.2836
*   CC: Tweaked version 1.12.2-1.82.2

crash report: http://paste.ubuntu.com/p/JW9J9CywMQ/
latest log: http://paste.ubuntu.com/p/TQk9rkY7HM/

log mentions silktouch, but that's stone he's facing
![image](https://user-images.githubusercontent.com/3880072/56459866-75beeb00-635f-11e9-8f2e-60919cf872cd.png)

**Comment by SquidDev** [comment] 2019-04-20 17:15
This looks to be a duplicate of #179. I'll try to get a release out in the next few days.

**Closed by SquidDev** 2019-04-20 17:15 UTC
