### ISSUE TITLE
Modems attached to turtles disappear on chunk unload

### ISSUE THREAD

**Issue by Lemmmy** [SquidDev-CC/CC-Tweaked#50] opened 2018-07-14 02:03 UTC
![](https://you.wouldnot.download/an-experienced-bronco.png)
![](https://you.wouldnot.download/a-spare-gall-bladder.png)

Replacing the turtle fixes the issue. The modem was first attached with the `equip` program, but it appears to happen too if it was crafted with the modem. The issue happens 100% of the time when unloading its chunk.

**Comment by SquidDev** [comment] 2018-10-31 10:28
Closing as I've been unable to reproduce and I don't believe it has occurred again. If anyone has additional info, please comment and I'll reopen.

**Comment by HydrantHunter** [comment] 2019-02-15 02:45
I'm having what may be the same issue.  When I go to the nether in one of my test worlds and come back to the overworld, all my overworld turtles have 'lost' their modems (even though the modems are still equipped and visible, they can't be seen via software).  The workaround I've used is to unequip and reequip the modems via startup script.

MC 1.12.2
Forge 14.23.5.2768
cc:Tweaked 1.80_pr1.14

I looked through the latest.log and the fml-client logs and found nothing worth posting.  About the only info I found was in my console log.

Here's the full log ... https://pastebin.com/Enz6L233

Here's just the salient part (play time) ... https://pastebin.com/REGMFU9R

The issue seems to be easy to reproduce for me (at least in this test world) so I'm happy to provide more info if required.  Also happy to test with a debug version if necessary.

**Closed** 2019-02-18 23:30 UTC
Labels: bug, cannot reproduce
