### ISSUE TITLE
Missing some turtle textures [Forge 1.20.1]

### ISSUE THREAD

**Issue by NirioFaid** [SquidDev-CC/CC-Tweaked#1607] opened 2023-10-09 17:22 UTC
### Minecraft Version

1.20.x

### Version

forge-1.108.3

### Details

Models/Textures for crafty, ender, wireless and noisy turtles are missing in JEI/game.

Using the latest version of Rubidium with Extras without Oculus/Shaders.

Other turtles are visually fine. Turtles with missing textures can be operated normally.

![Screenshot_44](https://github.com/cc-tweaked/CC-Tweaked/assets/55434483/35c35f01-f60b-4ff7-a13e-7a2a0e81b312)
![Screenshot_45](https://github.com/cc-tweaked/CC-Tweaked/assets/55434483/ebfeda33-aba8-4435-b115-77f758033af5)
![2023-10-09_21 18 42](https://github.com/cc-tweaked/CC-Tweaked/assets/55434483/5a13d07e-b328-4362-8599-fb05503a6fcc)

**Comment by SquidDev** [comment] 2023-10-09 17:42
I'm afraid I'm unable to reproduce this either with or without Rubidium, using Forge 47.1.0. Would you be able to upload your logs as well, which should include information about why the model failed to load.

**Comment by NirioFaid** [comment] 2023-10-09 18:53
After playing for a while textures just reappeared.

Logs from the time when I faced that issue and took screenshots above:

[2023-10-09-2.log](https://github.com/cc-tweaked/CC-Tweaked/files/12849480/2023-10-09-2.log)

**Comment by SquidDev** [comment] 2023-10-09 21:17
Oh, that's very odd. The log doesn't even include any model error messages.

I'm fairly confident this isn't a bug with CC:T here, so I'm afraid I'm going to close this issue. My suspicion is you've got a mod which interferes with model loading (maybe trying to make models load lazily), and they're not doing a very good job at it.

You might be able to try the classic "remove half the mods until it works/doesn't work", but otherwise I'm afraid I don't have any suggestions.

**Closed as not planned by SquidDev** 2023-10-09 21:17 UTC
Labels: bug, cannot reproduce, area-Minecraft
