### ISSUE TITLE
Crash when break speaker block

### ISSUE THREAD

**Issue by BlackJamesYT** [SquidDev-CC/CC-Tweaked#872] opened 2021-07-26 16:21 UTC
### Minecraft Version

1.16.x

### Version

1.97.0

### Details

Hey !

Minecraft crashes when I break a speaker block. 
I've tried with modded pickaxe, wooden pickaxe and creative.
Here logs with [crash-2021-07-26_18.18.03-client.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/6879765/crash-2021-07-26_18.18.03-client.txt)

Thank you c:

**Comment by SquidDev** [comment] 2021-07-26 16:23
Thanks for the report. This looks to be a duplicate of #867. I'm hoping to get a build with the fix in soonish.

**Closed by SquidDev** 2021-07-26 16:23 UTC
Labels: area-Minecraft, bug, duplicate
