### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by ValryonOmega** [SquidDev-CC/CC-Tweaked#1129] opened 2022-07-07 17:20 UTC
### Minecraft Version

1.19.x

### Version

cc-tweaked-1.19-1.100.8.jar

### Details

Actually using 1.19 but there is no option for that in the Version dropdown. Server crashing on launch, with no other mods installed and adding it to a personal use modpack
[2022-07-07-1.log](https://github.com/cc-tweaked/CC-Tweaked/files/9066036/2022-07-07-1.log)

**Comment by SquidDev** [comment] 2022-07-07 20:16
I'm afraid I can't reproduce this (testing with Forge 41.0.63). Are you sure those are your full logs, they look rather incomplete.

**Comment by ValryonOmega** [comment] 2022-07-12 02:27
Those are the complete logs, it just halts instantly when booting up. I am using Forge version 41.0.93. I did load up with version 41.0.63 and it did launch just fine. Something that is in the updated versions of Forge broke the mod. I didn't change anything but the Forge version and it now runs fine both client side and server side

**Comment by SquidDev** [comment] 2022-07-16 20:25
Fixed in 4a273ae8e5e3bbdb5addce0364f361c68ddc1990.

**Closed as completed by SquidDev** 2022-07-16 20:25 UTC
Labels: bug, cannot reproduce, area-Minecraft
