### ISSUE TITLE
Potential jade conflict

### ISSUE THREAD

**Issue by GodOfTheVoid** [SquidDev-CC/CC-Tweaked#1144] opened 2022-08-06 13:03 UTC
### Minecraft Version

1.18.x

### Version

1.100.9

### Details

Upon trying to use a computer, my game crashes. thanks to the crash utilities mod, jade came up, as a reason for the crash, as well as cc: tweaked. I can only suspect that there may be conflicts. i open the computer, and press any button, and it crashes almost immediately after.

https://bytebin.lucko.me/16BmaB4GTQ - crash report

[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/9275069/latest.log) - the log involved.

**Comment by SquidDev** [comment] 2022-08-06 13:14
I'm going to mark this as a duplicate of #979. There's a weird issue with Forge where you just get random NoClassDefFoundError errors, and I don't think anybody has worked out why.

**Closed as not planned by SquidDev** 2022-08-06 13:14 UTC
Labels: bug, duplicate, area-Minecraft
