### ISSUE TITLE
Add a Package Manager

### ISSUE THREAD

**Issue by ghost** [SquidDev-CC/CC-Tweaked#1697] opened 2024-01-26 02:35 UTC
How this would work is that anyone could upload a package to the network, and anyone with rednet can download it. You could also make it so that there can be different networks of packages.

**Comment by Wojbie** [comment] 2024-01-26 06:14
Duplicate of #425

**Comment by SquidDev** [comment] 2024-01-26 11:06
One of the tricky things about CC is deciding how to balance what functionality should be built-in to the mod and what we should just let individuals to write (or download) themselves.

As #425 and https://github.com/cc-tweaked/CC-Tweaked/pull/203#issuecomment-492148266 mention, package management (either over http or rednet) is a tricky one. In one sense, it would be good to have a standardised way of distributing and installing packages.

However, package management is really tricky to get *right*, and it's we have to get right first time. I'm not confident we can do that, so I'm afraid this is out-of-scope for right now. The CC community continues to experiment with different ways of handling package management, which you might want to check out!

**Closed as not planned by SquidDev** 2024-01-26 11:06 UTC
Labels: enhancement, wontfix, area-CraftOS
