### ISSUE TITLE
[1.15.2] PC crashes entire server

### ISSUE THREAD

**Issue by mcjojo3** [SquidDev-CC/CC-Tweaked#468] opened 2020-06-07 18:28 UTC
Soo whenever i place a CC pc in the world it automaticly crashes the game which isn't that nice. Here is the Crash Report: https://pastebin.com/DSaxSVjZ

**Comment by SquidDev** [comment] 2020-06-07 18:30
Duplicate of #463. This is an issue with Silent Mechanisms, but should be fixed now.

**Closed by SquidDev** 2020-06-07 18:30 UTC
Labels: bug

**Comment by mcjojo3** [comment] 2020-06-07 18:35
Ohh alright im sorry to waste your time but one hella fast support!

**Comment by SquidDev** [comment] 2020-06-07 18:38
No worries! Just checked - Silent mechanisms 0.7.2 should include the fix :).
