### ISSUE TITLE
Using optifine with CC: Tweaked

### ISSUE THREAD

**Issue by ChickenSquiggles** [SquidDev-CC/CC-Tweaked#1487] opened 2023-06-18 01:38 UTC
### Minecraft Version

1.19.x

### Version

1.101.2

### Details

The game crashes with the message when I add the correct version of optifine to the pack
`The game crashed whilst rendering overlay Error: java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.block.model.BakedQuad.<init>(int[], int, net.minecraft.core.Direction, net.minecraft.client.renderer.texture.TextureAtlasSprite, boolean, boolean)'`

Here is the crash report:
[https://pastebin.com/BtW1hwrN](url)

I have ensured I am using the correct version, and as well when I remove CC it runs fine with optifine.

**Comment by SquidDev** [comment] 2023-06-18 04:27
Duplicate of #1486.

**Closed as not planned by SquidDev** 2023-06-18 04:27 UTC
Labels: bug, duplicate, area-Minecraft
