### ISSUE TITLE
Server crashes after enabling http api on atm 8

### ISSUE THREAD

**Issue by Draphex** [SquidDev-CC/CC-Tweaked#1437] opened 2023-05-11 18:18 UTC
### Minecraft Version

1.19.x

### Version

1.101.2

### Details

I am playing on an All the Mods 8 server and after enabling the http api the server worked fine until a restart. After that the server would not start and crash constantly. Only disabling the http api again fixed the issue.

[message.txt](https://github.com/cc-tweaked/CC-Tweaked/files/11455292/message.txt)

**Comment by SquidDev** [comment] 2023-05-11 18:29
Thank you for the report. This looks to be a duplicate of #979, which is a nasty issue caused by Forge.

Would you be able to upload your full logs? That would be very helpful in tracking that down.

**Closed as not planned by SquidDev** 2023-05-11 18:29 UTC
Labels: bug, duplicate, area-Minecraft
