### ISSUE TITLE
Suggestion: Command Pocket Computers

### ISSUE THREAD

**Issue by AndrewScripter587** [SquidDev-CC/CC-Tweaked#1770] opened 2024-03-31 16:32 UTC
## Useful information to include:
 - Explanation of how the feature/change should work.
 - Some rationale/use case for a feature. My general approach to designing new features is to ask yourself "what issue are we trying to solve" and _then_ "is this the best way to solve this issue?".

I would like command pocket computers to be added. they would work the same way as command computers (that being they have access to commands, and can only be used if the player is in creative with operator permissions unless the server config option that enforces this is disabled), and are portable like pocket computers, and can have peripherals built in like pocket computers(like a noisy pocket computer having a built in speaker). I didn't see any other issues that have requested this, so I decided to request this myself.

I even made a texture for it:

![pocket_computer_command](https://github.com/cc-tweaked/CC-Tweaked/assets/145153158/2e89d928-faea-4e3f-ab1f-5737336154a9)

**Comment by Wojbie** [comment] 2024-03-31 17:25
Duplicate of https://github.com/cc-tweaked/CC-Tweaked/issues/1312 I think?

**Comment by AndrewScripter587** [comment] 2024-03-31 17:28
yeah i believe it is, but this suggestion can put more attention to the topic again.

I don't think it should be that hard to add though.

**Comment by SquidDev** [comment] 2024-03-31 20:10
I'm afraid I think my comments in the original issue still hold true today. I would like to overhaul the computer "family" system one day, to make this sort of thing possible, but I think pocket command computers are sufficiently niche that they're not worth implementing right now.

**Closed as not planned by SquidDev** 2024-03-31 20:10 UTC
Labels: duplicate, enhancement, area-Minecraft
