### ISSUE TITLE
Specify orientation of block being placed

### ISSUE THREAD

**Issue by MileyHollenberg** [SquidDev-CC/CC-Tweaked#628] opened 2020-12-26 17:19 UTC
Currently whenever you place a block or redstone component it places it facing forward depending on the turtle direction, what I would like to suggest is to also allow us to determine the orientation a block is place in. The way I could see this work would be something like this

turtle.place("north") always places it north regardless of the orientation of the turtle
turtle.place("left") places it left depending on the turtle orientation

The same idea would also apply to the up and down varieties.

The use-case here is similar to my previous feature request (#627) where it would be much easier to set the orientation of a redstone component. This would also apply for chests, stairs, slabs (top/bottom), fences, doors and so on and would give turtles more power when placing blocks without having to position itself in the perfect way without blocking itself in.

Currently the text parameter is being used for sign text and that functionality shouldn't be affected, maybe creating a separate function like turtle.placeOriented would make sense or the sign text could become the second parameter (though this would not be nice from a backward compatibility standpoint) but I'm not sure what the best way to go would be

**Comment by SquidDev** [comment] 2020-12-26 17:29
Duplicate of #204 I think. Basically it'd definitely be nice to do, but really not clear how it should be done.

**Closed by SquidDev** 2020-12-26 17:29 UTC
Labels: enhancement
