### ISSUE TITLE
Turtle Inventory not updating properly when mining blocks

### ISSUE THREAD

**Issue by wieselkatze** [SquidDev-CC/CC-Tweaked#300] opened 2019-09-29 12:05 UTC
### Useful information to include:
 - Minecraft version: 1.14.4
 - CC: Tweaked version: 1.84.1
 - Forge Version: 28.1.8
 - Detailed reproduction steps: 

Place down turtle and start some sort of mining operation that breaks a few blocks and stay in the GUI. As far as I know, the first block registers, but not subsequent ones. [EDIT]: I think it does not update any more as soon as the turtle traveled a block
[Turtle Mining blocks](https://imgur.com/a/kA7LZ6J)

This might correlate to #298.

**Comment by Knito58** [comment] 2019-10-01 21:41
Same problem with a felling turtle in a tree farm. The inventory of the turtle seems not to update properly while I am watching the print() debug Output and how the inventory is being used. After closing the GUI and reopening it, sometimes the items in the inventory are gone for good, sometimes they are raised in number due to harvest actions which did not update as long as I had the GUI open.

MC 1.14.4, Forge 28.1.26, CCT 1.84.1

The slots seem not to have the same weight. So is slot 1 great for saplings but this will be in the way when planks should be crafted for refuel. Moving the saplings to slot 16 resulted in a loss of all saplings as they are just overwritten by some harvested wood log and gone for good.

**Comment by Knito58** [comment] 2019-10-03 10:26
It's like Schroedinger's cat: May be working when left alone and not is looked at.

**Closed** 2019-10-04 18:47 UTC
Labels: area-Minecraft, bug, version-1.14.x

**Comment by Knito58** [comment] 2019-10-05 12:05
1.85.1 is fine now. Bugfix confirmed. Thank you.
