### ISSUE TITLE
Turtle dig ignores dripstone/deepslate (pickaxe and shovel equi[pped)

### ISSUE THREAD

**Issue by didier-a17** [SquidDev-CC/CC-Tweaked#1562] opened 2023-08-16 05:41 UTC
### Minecraft Version

1.20.x

### Version

1.107.0

### Details

Running an advanced turtle with iron tools digging me tunnels, the turtles completely ignore any dripstone or deepslate they encounter (which i expected them to dig)

**Comment by SquidDev** [comment] 2023-08-16 06:45
What do you mean by "ignores" here? Do you mean that the turtle cannot dig the block (so `turtle.dig()` returns `false, "Cannot break block with this tool"`), or something else?

CC:T doesn't include iron tools by default. Would you be able to upload your logs so I can see what other mods you have installed? I suspect this is MorePeripherals like in #1464, but just want to make sure.

**Comment by didier-a17** [comment] 2023-08-21 02:44
the turtle.dig does return false. Yes, MorePeriferals is installed

**Comment by SquidDev** [comment] 2023-08-21 06:22
Awesome, I'm going to mark this as a duplicate of #1464 then, just so we can track this in one place.

**Closed as not planned by SquidDev** 2023-08-21 06:22 UTC
Labels: bug, duplicate, area-Minecraft
