### ISSUE TITLE
Can't view printed page

### ISSUE THREAD

**Issue by WojAd** [SquidDev-CC/CC-Tweaked#897] opened 2021-08-18 14:13 UTC
### Minecraft Version

1.17.x

### Version

1.17.1-1.98

### Details

On Minecraft forge 1.17.1-37.0.34 I get an error while trying to view printed page. 

Message:

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.ShaderInstance.m_173350_(String, Object)" because "â˜ƒ" is null
Error code: -1

**Comment by SquidDev** [comment] 2021-08-18 14:16
This appears to be a duplicate of #894.

**Closed by SquidDev** 2021-08-18 14:16 UTC
Labels: bug, duplicate, area-Minecraft
