### ISSUE TITLE
EnderStorage Enderchest reset if turtle.place()

### ISSUE THREAD

**Issue by thewho333** [SquidDev-CC/CC-Tweaked#214] opened 2019-05-20 19:44 UTC
Minecraft: 1.12.2
CC: Tweaked 1.82.3 (newest)
Enderstorage: 2.4.5.135 (newest)
Pack: FTB Ultimate Reloaded (with CC:Tweaked added)

Bug/configerror(?)
If a turtle places a colored(!) enderchest from the mod "enderstorage" it resets to the default "white, white, white, no diamond" which means only one player can use for example a mining script that uses enderchests.
I also got a server crash when right clicking a Thermal Expansion strongbox that a turtle has placed. Sorry, no I don't have the log file.

**Comment by thewho333** [comment] 2019-05-20 20:42
I'm sorry, seems to be a Enderstorage bug
[https://github.com/TheCBProject/EnderStorage/issues/70](url)

**Comment by thewho333** [comment] 2019-05-21 07:02
Tried "Octahedroid" and that's the same. Resets to channel 0 every time a turtle places one

**Comment by SquidDev** [comment] 2019-05-26 15:21
I'm unable to reproduce the EnderStorage or Thermal Expansion issue. Octahedroids don't appear to preserve their channel when broken for me, so I wasn't able to try that one at all.

Tried using just the following mod versions:
 - **Forge**: 14.23.4.2749 or 14.23.5.2838.
 - **CC:Tweaked**: 1.82.3
 - **CodeChickenLib**: 3.2.2.353
 - **CoFHCore**: 4.6.3.26
 - **CoFHWorld**: 1.3.1.7
 - **EnderStorage**: 2.4.5.135
 - **Octahedroid**: 1.0.3
 - **RedstoneFlux**: 1.12-2.1.0.6
 - **ThermalExpansion**: 5.5.4.43
 - **ThermalFoundation**: 2.6.3.27

It's possible there's another mod messing with block placing logic - if you can still reproduce this, it may be worth doing the standard binary search - remove half the mods, until you can find a minimal set under which the issue still occurs.

**Comment by admiral0** [comment] 2019-06-14 00:25
I can reproduce with turtle.place() -> the ender chest resets to white/white/white.

Will investigate more this weekend

**Comment by admiral0** [comment] 2019-06-14 01:38
my hypothesis is https://github.com/SquidDev-CC/CC-Tweaked/blob/7d428030df1995c347759837676cf56fd2703872/src/main/java/dan200/computercraft/shared/turtle/core/TurtlePlaceCommand.java#L358 succeeds - it's an operation on an Item, not ItemStack.

**Comment by SquidDev** [comment] 2019-06-14 07:12
@admiral0 If you were able to reproduce, can your logs, and a list of mods you were using. As mentioned earlier up, I can't reproduce with just CC:T and any of those mods, so I suspect something else is interfering. 

The code you linked should be fine - `ItemStack.onItemUseFirst` just looks like this:
```java
EnumActionResult result = getItem().onItemUseFirst(playerIn, worldIn, pos, side, hitX, hitY, hitZ, hand);
if (result == EnumActionResult.SUCCESS) {
  playerIn.addStat(StatList.getObjectUseStats(this.item));
}
return result;
```

We're not doing anything radically different - just not incrementing the stat on the fake player (though truth be told, that change is probably superfluous).

**Comment by admiral0** [comment] 2019-06-14 08:18
Will try to reproduce this evening (UTC) in a controlled environment where I can step debug and see if I can figure it out. Could you reopen this in the meantime?

**Comment by admiral0** [comment] 2019-06-14 20:34
I managed to exclude forge version difference as root cause. Trying to get my whole modpack loading in IntelliJ :D

**Comment by admiral0** [comment] 2019-06-15 19:30
Found the culprit. 

Minimal setup required to trigger the issue between ender chests and turtles. Weirdly enough it;s the Immersive Railroading mod. Mods:
```
Forge: 14.23.5.2838
CC:Tweaked 1.83.1
CodeChickenLib: 3.2.2.353
EnderStorage: 2.4.5.135
Track Api: 1.1 <- dependency
ImmersiveEngineering 0.12-89 <- dependency, no issue by itself
ImmersiveRailroading 1.6.1 <- culprit
```

**Comment by thewho333** [comment] 2019-06-15 19:43
Thank you! I removed Immersive Railroading and it works as intended.

**Comment by SquidDev** [comment] 2019-07-30 14:27
This doesn't appear to be an issue on my end, so closing this for now.

**Closed** 2019-07-30 14:27 UTC
Labels: bug, cannot reproduce
