### ISSUE TITLE
JEI Rendering tooltip

### ISSUE THREAD

**Issue by Seniorendi** [SquidDev-CC/CC-Tweaked#759] opened 2021-04-10 23:49 UTC
Hovering over a turtle upgrade recipe throws an issue and nothing renders.
More information: https://github.com/Seniorendi/AdvancedPeripherals/issues/51

Or should i report that to JEI?

## Useful information to include:
 - Minecraft version: 1.16.5
 - CC: Tweaked version: 1.95.3
 - Logs: Snippet of an exception: https://gist.github.com/Seniorendi/5bc3e5ba3040a04ed65286e87a5857f4
 - Detailed reproduction steps: Hover over a turtle upgrade, not the normal turtle recipe

**Comment by SquidDev** [comment] 2021-04-11 08:57
I believe this is a duplicate of #719, which should have been fixed in b17ff6daf03e0be2b919a2cab3846ac6b0b6cd45 - it's just not been released yet.

**Closed by SquidDev** 2021-04-11 08:57 UTC
Labels: area-Minecraft, bug, duplicate
