### ISSUE TITLE
turtles can't see equipped items if chunk unloads

### ISSUE THREAD

**Issue by Solarflame5** [SquidDev-CC/CC-Tweaked#117] opened 2019-02-16 13:18 UTC
if the chunk the turtle is in unloads, the turtle cant see anything equipped on it until either you pickaxe and replace the turtle or unequip every item and equip back,

**Comment by SquidDev** [comment] 2019-02-16 13:35
Duplicate of #50. I've been unable to find a reliable way to reproduce in a single player world, so any additional info would be much appreciated.

**Closed by SquidDev** 2019-02-16 13:35 UTC
