### ISSUE TITLE
Monitor breaks when chunk unloaded.

### ISSUE THREAD

**Issue by alucard87pl** [SquidDev-CC/CC-Tweaked#1703] opened 2024-01-28 12:33 UTC
### Minecraft Version

1.20.x

### Version

1.109.3

### Details

I run a program that draws something on the monitor. When I go far away and come back the screen is black. Resetting the computer does not help.  Only breaking and placing the monitor again solves the problem. I temporarily use a chunkloader to prevent this from happening.

**Comment by SquidDev** [comment] 2024-01-28 13:40
Thanks for the report. This appears to be the same issue as https://github.com/cc-tweaked/CC-Tweaked/issues/1560, so I'm going to close this in favour of that. 

I'm afraid I've been entirely unable to reproduce the underlying issue. If you've got a reliable way to reproduce it with just CC, that would be very useful to know.

**Closed as not planned by SquidDev** 2024-01-28 13:40 UTC
Labels: bug, duplicate, area-Minecraft
