### ISSUE TITLE
Turtles are also inventory

### ISSUE THREAD

**Issue by suhedge** [SquidDev-CC/CC-Tweaked#1919] opened 2024-07-30 11:54 UTC
## Useful information to include:
 - Explanation of how the feature/change should work.
 - Some rationale/use case for a feature. My general approach to designing new features is to ask yourself "what issue are we trying to solve" and _then_ "is this the best way to solve this issue?".

I tried to write storage server and related things for some time. One of strange things i encountered: turtles dont have methods to transfer items, which makes it impossible to transfer items strait between turtles requiring some buffer storage between.
I thing that making peripherals have multiple types will solve that issue, so then wrapping turtle as peripheral methods for both _pc_ and _generic inventory_ are exposed.

There probably exist similar issue when block have both fluid and item storage, but i am not checked that.

**Comment by SquidDev** [comment] 2024-07-30 12:23
Thanks for the issue! I think this is a duplicate of #1392, so going to close it in favour of that.

**Closed as not planned** 2024-07-30 19:59 UTC
Labels: duplicate, enhancement, area-Minecraft
