### ISSUE TITLE
turtle place up ladder sometimes wrong return value

### ISSUE THREAD

**Issue by gogedo** [SquidDev-CC/CC-Tweaked#1433] opened 2023-05-07 18:44 UTC
### Minecraft Version

1.19.x

### Version

cc-tweaked-1.19.2-1.101.2

### Details

pastebin get Mk5x46k2 test.lua
----- test.lua    place up ladder  in shaft (Flat Surface) 

for i=1,5 do
turtle.digDown()
turtle.down()
print(turtle.placeUp())
end

------------------

getting:
false Cannot place block here  (ok)
true                                           (ok)
false Cannot place block here  (wrong)                 turtle places the ladder !
false Cannot place block here  (wrong)                 turtle places the ladder !
false Cannot place block here  (wrong)                 turtle places the ladder !

cc-tweaked-1.12.2-1.89.2
getting:
false Cannot place block her (ok)
true                                        (ok)
true                                        (ok)
true                                        (ok)
true                                        (ok)

**Comment by SquidDev** [comment] 2023-05-08 08:08
Thank you for the report!

I've been unable to reproduce locally (both on 1.19.2 and 1.19.4). On a super-flat world, I get the same output as 1.12.2.

Are you using any mods here, or is this just with CC:T? I wonder if there's a mod which replaces ladder placing logic, and that confuses CC.

**Comment by gogedo** [comment] 2023-05-09 18:35
It is a flat surface in a normal world **ATM8** . So first ladder cannot place.
If there is a block in front of turtle all ladders will be placed

**Comment by gogedo** [comment] 2023-05-09 18:56
I test only with mod cc and all works fine! Must be another matter.

**Comment by gogedo** [comment] 2023-05-09 20:06
Direwolf20 1.19 1.0.1 same Problem
must be a mod being in both modpacks

**Comment by SquidDev** [comment] 2023-05-09 22:02
Thank you for testing and narrowing it down, that's incredibly helpful! I _suspect_ this is a vanilla plus mod (so something like quark)[^1] - I'm afraid I'm on holiday right now, but will have a closer look next week.

[^1]: Just to clarify here, this is almost definitely a CC:T bug, not a problem with the other mod. Just looking for how to reproduce this!

**Comment by gogedo** [comment] 2023-05-09 23:05
Thank's
It's a miracle that the first ladder placed in shaft  get "true" as they could "see" 2 block's above after going down.
I check it out  with only print(turtle.placeUp()) on a tree.

Ok, only if there are 2 Blocks above a same kind of ladder then come wrong message
differend ladder or other Block's are correctly.
That's crazy...

**Comment by SquidDev** [comment] 2023-05-21 10:27
Yep, this is caused by Quark's "Enhanced Ladder's" module. They [cancel the block placement](https://github.com/VazkiiMods/Quark/blob/0c1c0317d7f62aa15a965f873209a999ef1a0358/src/main/java/vazkii/quark/content/tweaks/module/EnhancedLaddersModule.java#L114-L115) in order to provide custom behaviour, but this means that the turtle doesn't think the block has been placed.

I actually think this is something that can be fixed on Quark's end - will have a look at putting a PR together.

**Closed as completed** 2023-05-21 10:55 UTC
Labels: bug, area-Minecraft
