### ISSUE TITLE
[1.13.3] Crash on starting NPE ClientRegistry.onItemColours

### ISSUE THREAD

**Issue by ProsperCraft** [SquidDev-CC/CC-Tweaked#159] opened 2019-03-28 01:03 UTC
https://gist.github.com/ProsperCraft/acf459a107f477408d4ac303f892c4ca

I am putting together a mash pack where I put all of the mods together and make them angry, this is my first crash.

**Comment by SquidDev** [comment] 2019-03-28 06:38
I suspect this in a duplicate of #154. Can you try the jar attached there?

**Closed** 2019-03-29 10:47 UTC
Labels: bug, duplicate
