### ISSUE TITLE
Turtles/Computers not dropping upon breaking

### ISSUE THREAD

**Issue by THeExUduS** [SquidDev-CC/CC-Tweaked#430] opened 2020-04-28 12:12 UTC
## Problem:
Started a normal survival world on my server. Any turtle or computer will not drop itself when broken by the player (didn't test breaking by explosion). Breaking animation starts normally, but when the block is about to drop nothing happens and no particles appear.

Only encountered on CC:Tweaked's blocks, that execute code (including command computer).
Any other block, e.g. cable, monitor, etc. works perfectly fine.
Game never crashes when breaking those blocks.

**Attention**: About 25 other mods were loaded when the problem first occured. Without those mods the problem still exists, so the mods are probably not the cause.

**No** config files of any mod were changed.

Changed to forge 31.1.62, but still experience the problem mentioned.
Occurs on singleplayer (local world) and multiplayer (my server pc hosting the world).

## Mod list:
(only curseforge downloads)

AdLods-1.15.2-3.0.1.0-build.0008
AppleSkin-mc1.15.2-forge-1.0.13
AttributeFix-1.15.2-7.0.2
BiomesOPlenty-1.15.2-10.0.0.345-universal
cc-tweaked-1.15.2-1.87.0
CraftTweaker-1.15.2-6.0.0.17
FastLeafDecay-v22
FluxNetworks-1.15.2-5.0.1-2
ForgeEndertech-1.15.2-6.0.2.1-build.0024
Hwyla-forge-1.10.8-B72_1.15.2
jei-1.15.2-6.0.0.3
journeymap-1.15.2-5.7.0beta1
lithium-mc1.15.2-forge-0.4.6-rc3-mod
Mekanism-1.15.2-9.10.1.414
MekanismGenerators-1.15.2-9.10.1.414
MixinBootstrap-1.0.2
MouseTweaks-2.13-mc1.15.1
Neat+1.6-20
OreExcavation-1.7.151
phosphor-forge-mc1.15.2-0.5.2+build.4
ProgressiveBosses-2.1.5-mc1.15.2
refinedstorage-1.8.1
refinedstorageaddons-0.6.1
swingthroughgrass-1.15.2-1.4.0
theoneprobe-1.15-2.0.2

## Versions:
 - Minecraft version: 1.15.2
 - Forge version: 31.1.47, 31.1.62
 - CC: Tweaked version: 1.15.2-1.87.0
 - Detailed reproduction steps:
1. Install forge version
2. Install mods
3. Join a minecraft world/server
4. Place and break a computer/turtle

## Information (from local world):
[2020-04-28-2.log](https://github.com/SquidDev-CC/CC-Tweaked/files/4545464/2020-04-28-2.log)
[latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/4545491/latest.log)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3340087776 bytes (3185 MB) / 4429185024 bytes (4224 MB) up to 21474836480 bytes (20480 MB)
	CPUs: 4
	Launched Version: 1.15.2-forge-31.1.47
	Type: Client (map_client.txt)
	CPU: i5-7600K
        GPU: Geforce GTX 1080

**JVM Arguments in Profile:**
-Xmx20G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Comment by SquidDev** [comment] 2020-04-28 12:14
This was a bug in 1.87.0 (see #421) - could you update to that and confirm it fixes your problem?

**Comment by THeExUduS** [comment] 2020-04-28 12:21
Updating CC:Tweaked to 1.87.1 fixes the problem.
Particles don't appear, but thats the minor problem.
Solved.

**Comment by SquidDev** [comment] 2020-04-29 15:16
Closing as duplicate of #421. I was unable to reproduce the particle issue - it appears fine in dev in Forge 31.1.41.

**Closed by SquidDev** 2020-04-29 15:16 UTC
Labels: area-Minecraft, bug, version-1.15.x
