### ISSUE TITLE
Game crashes with Computercraft

### ISSUE THREAD

**Issue by Minecraft2p0** [SquidDev-CC/CC-Tweaked#534] opened 2020-09-02 19:00 UTC
The game crashed with the command turtle.placeDown () and using a pair of scissors. On the second attempt, my PC even switched off. I had to reinstall Minecraft to get it to work again. Enclosed the crash report.
So far, CC ran without any problems under this version.

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 02.09.20 20:32
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at dan200.computercraft.shared.turtle.core.TurtlePlaceCommand.deployOnEntity(TurtlePlaceCommand.java:249) ~[?:1.91.0] {re:classloading}
	at dan200.computercraft.shared.turtle.core.TurtlePlaceCommand.deploy(TurtlePlaceCommand.java:121) ~[?:1.91.0] {re:classloading}
	at dan200.computercraft.shared.turtle.core.TurtlePlaceCommand.execute(TurtlePlaceCommand.java:81) ~[?:1.91.0] {re:classloading}
	at dan200.computercraft.shared.turtle.core.TurtleBrain.updateCommands(TurtleBrain.java:769) ~[?:1.91.0] {re:classloading}
	at dan200.computercraft.shared.turtle.core.TurtleBrain.update(TurtleBrain.java:129) ~[?:1.91.0] {re:classloading}
	at dan200.computercraft.shared.turtle.blocks.TileTurtle.func_73660_a(TileTurtle.java:217) ~[?:1.91.0] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:366) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$7020/2125101298.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at dan200.computercraft.shared.turtle.core.TurtlePlaceCommand.deployOnEntity(TurtlePlaceCommand.java:249)
	at dan200.computercraft.shared.turtle.core.TurtlePlaceCommand.deploy(TurtlePlaceCommand.java:121)
	at dan200.computercraft.shared.turtle.core.TurtlePlaceCommand.execute(TurtlePlaceCommand.java:81)
	at dan200.computercraft.shared.turtle.core.TurtleBrain.updateCommands(TurtleBrain.java:769)
	at dan200.computercraft.shared.turtle.core.TurtleBrain.update(TurtleBrain.java:129)
	at dan200.computercraft.shared.turtle.blocks.TileTurtle.func_73660_a(TileTurtle.java:217)

-- Block entity being ticked --
Details:
	Name: computercraft:turtle_advanced // dan200.computercraft.shared.turtle.blocks.TileTurtle
	Block: Block{computercraft:turtle_advanced}[facing=west,waterlogged=false]
	Block location: World: (-1556,65,592), Chunk: (at 12,4,0 in -98,37; contains blocks -1568,0,592 to -1553,255,607), Region: (-4,1; contains chunks -128,32 to -97,63, blocks -2048,0,512 to -1537,255,1023)
	Block: Block{computercraft:turtle_advanced}[facing=west,waterlogged=false]
	Block location: World: (-1556,65,592), Chunk: (at 12,4,0 in -98,37; contains blocks -1568,0,592 to -1553,255,607), Region: (-4,1; contains chunks -128,32 to -97,63, blocks -2048,0,512 to -1537,255,1023)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:491)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:366)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Dreissen075'/99, l='ServerLevel[Livin´ together]', x=-1553.82, y=63.00, z=594.39]]
	Chunk stats: ServerChunkCache: 9043
	Level dimension: minecraft:overworld
	Level spawn location: World: (-224,65,-224), Chunk: (at 0,4,0 in -14,-14; contains blocks -224,0,-224 to -209,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 411375 game time, 653685 day time
	Level name: Livin´ together
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 29779 (now: false), thunder time: 74692 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229)
	at net.minecraft.server.MinecraftServer$$Lambda$7020/2125101298.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4607998352 bytes (4394 MB) / 7247757312 bytes (6912 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.2-33.0.23.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.23.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.2-33.0.23.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.23.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.2_HD_U_G3_pre4.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.2-33.0.23.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.2-0.2.4.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.2-0.2.4.jar optiforge TRANSFORMATIONSERVICE 
	FML: 33.0
	Forge: net.minecraftforge:33.0.23
	FML Language Providers: 
		javafml@33.0
		minecraft@1
	Mod List: 
		forge-1.16.2-33.0.23-client.jar Minecraft {minecraft@1.16.2 DONE}
		DrawersTooltip-1.16.2-2.1.0.jar Drawers Tooltip {drawerstooltip@2.1.0 DONE}
		backpacked-1.5.1-1.16.1.jar Backpacked {backpacked@1.5.1 DONE}
		theoneprobe-1.16-3.0.4-beta.jar The One Probe {theoneprobe@1.16-3.0.4-beta DONE}
		forgeautofish-1.0.5-1.16.2.jar AutoFish for Forge {forgeautofish@1.0.4 DONE}
		worldedit-forge-mc1.16.2-7.2.0-beta-04.jar WorldEdit {worldedit@7.2.0-beta-04+98f71a3 DONE}
		mcjtylib-1.16-5.0.4.jar McJtyLib {mcjtylib@1.16-5.0.4 DONE}
		CreativeCore_v2.0.7_mc1.16.2.jar CreativeCore {creativecore@2.0.0 DONE}
		cc-tweaked-1.16.2-1.91.0.jar CC: Tweaked {computercraft@1.91.0 DONE}
		beenfo-1.16.2-forge33.0.5-1.1.5.jar Beenfo {beenfo@1.16.2-forge33.0.5-1.1.5 DONE}
		jei-1.16.2-7.3.2.25.jar Just Enough Items {jei@7.3.2.25 DONE}
		ItemPhysic_v1.4.6_mc1.16.2.jar ItemPhysic {itemphysic@1.6.0 DONE}
		OptiForge-MC1.16.2-0.2.4.jar OptiForge {optiforge@0.2.4 DONE}
		forge-1.16.2-33.0.23-universal.jar Forge {forge@33.0.23 DONE}
		torohealth-1.16.2-forge-2.jar ToroHealth {torohealth@NONE DONE}
		rftoolsbase-1.16-2.0.3-beta.jar RFToolsBase {rftoolsbase@1.16-2.0.3-beta DONE}
		rftoolsutility-1.16-3.0.6-beta.jar RFToolsUtility {rftoolsutility@1.16-3.0.6-beta DONE}
		rftoolsbuilder-1.16-3.0.3-beta.jar RFToolsBuilder {rftoolsbuilder@1.16-3.0.3-beta DONE}
		Xaeros_Minimap_20.20.2.1_Forge_1.16.2.jar Xaero's Minimap {xaerominimap@20.20.2 DONE}
		rftoolsstorage-1.16-2.0.3-beta.jar RFToolsStorage {rftoolsstorage@1.16-2.0.3-beta DONE}
		XaerosWorldMap_1.10.2.1_Forge_1.16.2.jar Xaero's World Map {xaeroworldmap@1.10.2 DONE}
		corpse-1.16.2-1.0.8.jar Corpse {corpse@1.16.2-1.0.8 DONE}
		[1.16.2]+SecurityCraft+v1.8.19.3.jar SecurityCraft {securitycraft@v1.8.19.3 DONE}
		StorageDrawers-1.16.2-8.1.0.jar Storage Drawers {storagedrawers@1.16.2-8.1.0 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['Dreissen075'/99, l='ServerLevel[Livin´ together]', x=-1553.82, y=63.00, z=594.39]]
	Data Packs: vanilla, mod:drawerstooltip, mod:backpacked (incompatible), mod:theoneprobe, mod:forgeautofish (incompatible), mod:worldedit (incompatible), mod:mcjtylib, mod:creativecore (incompatible), mod:computercraft, mod:beenfo (incompatible), mod:jei, mod:itemphysic (incompatible), mod:optiforge (incompatible), mod:forge (incompatible), mod:torohealth (incompatible), mod:rftoolsbase, mod:rftoolsutility, mod:rftoolsbuilder, mod:xaerominimap, mod:rftoolsstorage, mod:xaeroworldmap, mod:corpse, mod:securitycraft (incompatible), mod:storagedrawers (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.2_HD_U_G3_pre4
	OptiFine Build: 20200825-180551
	Render Distance Chunks: 30
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-Renewed-v1.0.1.zip
	OpenGlVersion: 4.6.0 NVIDIA 452.06
	OpenGlRenderer: GeForce RTX 2070 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by SquidDev** [comment] 2020-09-02 19:56
Duplicate of #531. Sorry, I entirely forgot to actually put out a new release.

**Closed by SquidDev** 2020-09-02 19:56 UTC
Labels: area-Minecraft, bug, duplicate, version-1.16.x
