### ISSUE TITLE
Monitor occasionally causes client to crash.

### ISSUE THREAD

**Issue by cflip** [SquidDev-CC/CC-Tweaked#477] opened 2020-06-21 02:41 UTC
Problem with CC:T 1.89.0 on Minecraft 1.12.2. 

I sometimes get crashes when placing monitors or running programs that use the monitor. I looked through the log but couldn't find any obvious errors. This doesn't happen every time, maybe every 3 or 4 uses of the monitor. When other people are also looking in the direction of the monitor in a multiplayer they experience the same thing, leading me to believe it is a bug with the rendering. 

[Log file](https://github.com/SquidDev-CC/CC-Tweaked/files/4808841/latest.log)
![Screenshot of crash](https://user-images.githubusercontent.com/36554078/85215468-5aba8300-b336-11ea-86c0-16133c679ac0.png)

**Comment by SquidDev** [comment] 2020-06-21 11:05
Thanks for the report! This appears to be a duplicate of #476 - I'm putting together a fixed build now.

**Closed by SquidDev** 2020-06-21 11:05 UTC
Labels: area-Minecraft, bug

**Comment by StriderTR** [comment] 2022-07-20 08:34
EDIT: Moved to new issue, it's late, and I didn't realize this issue was closed.

[https://github.com/cc-tweaked/CC-Tweaked/issues/1137](https://github.com/cc-tweaked/CC-Tweaked/issues/1137)
