### ISSUE TITLE
Bug with disk.hasAudio and disk.playAudio functions

### ISSUE THREAD

**Issue by Out-Feu** [SquidDev-CC/CC-Tweaked#706] opened 2021-02-05 14:28 UTC
Hello,

I tried using the disk.hasAudio and disk.playAudio functions on the Direwolf20 1.16 modpack and it seems that they don't work.

The disk.isPresent and disk.getAudioTitle functions return what they are supposed to.
But the disk.hasAudio always return false, and the disk.playAudio doesn't play the music disc.

I tried with multiple vanilla and modded music discs in singleplayer and in multiplayer with the same result.
I also tried using a speaker to play the sound associated with the music discs, and it worked.

Minecraft Version: 1.16.4
CC: Tweaked Version: 1.95.2
Forge Version: 35.1.36
Modpack: FTB Presents Direwolf20 1.16 
Modpack Version 1.5.1

Setup:
![ccSetup](https://user-images.githubusercontent.com/13755163/107043847-d3862680-67c3-11eb-90e5-7f23b2ab9808.JPG)

Code:
![ccCode](https://user-images.githubusercontent.com/13755163/107043782-c0735680-67c3-11eb-9d99-a9c4d4629c9f.JPG)

Result:
![ccResult](https://user-images.githubusercontent.com/13755163/107043823-cb2deb80-67c3-11eb-9890-d3ea62f865c3.JPG)

**Comment by SquidDev** [comment] 2021-02-05 20:56
Duplicate of #688, which was fixed in 657ceda3af035291413efd714a199786a755f558 but hasn't been released yet.

**Closed by SquidDev** 2021-02-05 20:56 UTC
Labels: bug
