### ISSUE TITLE
All computers have id 1

### ISSUE THREAD

**Issue by Bennett-dev** [SquidDev-CC/CC-Tweaked#1451] opened 2023-05-20 18:38 UTC
### Minecraft Version

1.19.x

### Version

1.101.2

### Details

I Have a 1.19.2 43.2.11 forge server with 8G of ram, and all the computer have id 1 i have tried changing the nbt tags but that didn't 

here's the mod list:

architectury-6.5.82-forge.jar
betteranimalsplus-1.19.2-11.0.10-forge.jar
cc-tweaked-1.19.2-1.101.2.jar
cfm-7.0.0-pre34-1.19.jar
cgm-1.3.4-1.19.2.jar
ChargedExplosives-1.19.2-1.0.0-1.jar
create-1.19.2-0.5.0.i.jar
flywheel-forge-1.19.2-0.6.8.a.jar
framework-0.4.2-1.19.2.jar
immersive_aircraft-0.4.2+1.19.2-forge.jar
jei-1.19.2-forge-11.4.0.286.jar
mcw-doors-1.0.9forge-mc1.19.2.jar
MfE+2.0.0.jar
moonlight-1.19.2-2.2.33-forge.jar
movingelevators-1.4.2-forge-mc1.19.jar
MTR-forge-1.19.2-3.1.6.jar
rsgauges-1.19.2-forge-1.2.18.jar
simpleplanes-1.19.2-5.2.2.jar
supermartijn642configlib-1.1.6b-forge-mc1.19.jar
supermartijn642corelib-1.1.7-forge-mc1.19.jar
supplementaries-1.19.2-2.3.10.jar
Xaeros_Minimap_23.4.3_Forge_1.19.1.jar
[1.19.2]+SecurityCraft+v1.9.6.1.jar

**Comment by Lupus590** [comment] 2023-05-21 00:49
What are you doing to create the computers?
Did this start happening after a mod update? If so then which mods did you update?
Can you try to replicate the bug with as few mods as you can?

**Comment by SquidDev** [comment] 2023-05-21 09:12
I'm unable to reproduce this with just CC: Tweaked. Would you be able to post your logs as well?

**Comment by SquidDev** [comment] 2023-06-02 18:39
I'm going to close this as I've been unable to reproduce this. If folks have more information, happy to reopen this again.

**Closed as not planned by SquidDev** 2023-06-02 18:39 UTC
Labels: bug, cannot reproduce, area-Minecraft

**Comment by Bennett-dev** [comment] 2023-07-16 19:40
sorry i took so long heres the latest.log:


[21May2023 11:13:42.253] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 43.2.11, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[21May2023 11:13:42.266] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.1 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[21May2023 11:13:43.123] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/me's%20Gaming%20PC/Documents/forge%201.19.2%20server/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2363!/ Service=ModLauncher Env=SERVER
[21May2023 11:13:43.645] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\me's Gaming PC\Documents\forge 1.19.2 server\libraries\net\minecraftforge\fmlcore\1.19.2-43.2.11\fmlcore-1.19.2-43.2.11.jar is missing mods.toml file
[21May2023 11:13:43.650] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\me's Gaming PC\Documents\forge 1.19.2 server\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.2.11\javafmllanguage-1.19.2-43.2.11.jar is missing mods.toml file
[21May2023 11:13:43.655] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users/me's Gaming PC\Documents\forge 1.19.2 server\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.2.11\lowcodelanguage-1.19.2-43.2.11.jar is missing mods.toml file
[21May2023 11:13:43.660] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\me's Gaming PC\Documents\forge 1.19.2 server\libraries\net\minecraftforge\mclanguage\1.19.2-43.2.11\mclanguage-1.19.2-43.2.11.jar is missing mods.toml file
[21May2023 11:13:43.832] [main/WARN] [net.minecraftforge.jarjar.selection.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: flywheel. Using Mod File: C:\Users\me's Gaming PC\Documents\forge 1.19.2 server\mods\flywheel-forge-1.19.2-0.6.8.a.jar
[21May2023 11:13:43.833] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 1 dependencies adding them to mods collection
[21May2023 11:13:45.884] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[21May2023 11:13:45.929] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
[21May2023 11:13:46.654] [main/WARN] [mixin/]: Error loading class: vectorwing/farmersdelight/common/block/TomatoVineBlock (java.lang.ClassNotFoundException: vectorwing.farmersdelight.common.block.TomatoVineBlock)
[21May2023 11:13:46.656] [main/WARN] [mixin/]: @Mixin target vectorwing.farmersdelight.common.block.TomatoVineBlock was not found supplementaries.mixins.json:CompatFarmersDelightMixin
[21May2023 11:13:53.737] [main/INFO] [net.minecraft.util.datafix.DataFixers/]: Building unoptimized datafixer
[21May2023 11:13:57.833] [modloading-worker-0/INFO] [wile.rsgauges.ModRsGauges/]: Gauges and Switches GIT id #ea5e550.
[21May2023 11:13:59.132] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id architectury:sync_ids
[21May2023 11:13:59.702] [modloading-worker-0/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 43.2.11, for MC 1.19.2 with MCP 20220805.130853
[21May2023 11:13:59.702] [modloading-worker-0/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v43.2.11 Initialized
[21May2023 11:14:00.240] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_generate_path
[21May2023 11:14:00.245] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_clear_trains
[21May2023 11:14:00.247] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_sign_types
[21May2023 11:14:00.248] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_add_balance
[21May2023 11:14:00.249] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_pids_update
[21May2023 11:14:00.250] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_arrival_projector_update
[21May2023 11:14:00.253] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_use_time_and_wind_sync
[21May2023 11:14:00.271] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_update_station
[21May2023 11:14:00.273] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_update_platform
[21May2023 11:14:00.274] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_update_siding
[21May2023 11:14:00.277] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_update_route
[21May2023 11:14:00.283] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_update_depot
[21May2023 11:14:00.287] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_update_lift
[21May2023 11:14:00.290] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_update_lift_track_floor
[21May2023 11:14:00.300] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_delete_station
[21May2023 11:14:00.301] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_delete_platform
[21May2023 11:14:00.301] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_delete_siding
[21May2023 11:14:00.302] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_delete_route
[21May2023 11:14:00.305] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_delete_depot
[21May2023 11:14:00.307] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_update_train_announcer
[21May2023 11:14:00.312] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_remove_rail_action
[21May2023 11:14:00.315] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:update_train_passenger_position
[21May2023 11:14:00.316] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:update_lift_passenger_position
[21May2023 11:14:00.316] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:update_entity_seat_position
[21May2023 11:14:00.317] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_drive_train
[21May2023 11:14:00.317] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id mtr:packet_press_lift_button
[21May2023 11:14:00.432] [modloading-worker-0/INFO] [dev.itsmeow.betteranimalsplus.BetterAnimalsPlusMod/]: Injecting super coyotes...
[21May2023 11:14:00.443] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id betteranimalsplus:main_channel/23ca639241d73eaf919246602470f295
[21May2023 11:14:00.461] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id betteranimalsplus:main_channel/d8f3c48219d933a6b2302c4d780df514
[21May2023 11:14:00.466] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id betteranimalsplus:main_channel/dd94e2f3f0db361b8621d0f834adec1b
[21May2023 11:14:00.483] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id betteranimalsplus:main_channel/59f1974289d63eb58cbd6fe813098096
[21May2023 11:14:00.488] [modloading-worker-0/INFO] [dev.architectury.networking.forge.NetworkManagerImpl/]: Registering C2S receiver with id betteranimalsplus:main_channel/fd8d1482ead03ca8a9954263aa7f6289
[21May2023 11:14:00.571] [modloading-worker-0/INFO] [mtr.libraries.org.eclipse.jetty.util.log/]: Logging initialized @20830ms to mtr.libraries.org.eclipse.jetty.util.log.Slf4jLog
[21May2023 11:14:05.454] [main/INFO] [moonlight/]: Initialized block sets in 64ms
[21May2023 11:14:06.346] [Thread-0/INFO] [wile.rsgauges.ModRsGauges/]: Config file changed rsgauges-common.toml
[21May2023 11:14:06.479] [modloading-worker-0/INFO] [dev.itsmeow.betteranimalsplus.BetterAnimalsPlusMod/]: Overspawning lammergeiers...
[21May2023 11:14:06.570] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [moonlight] Starting version check at https://raw.githubusercontent.com/MehVahdJukaar/Moonlight/multi-loader/forge/update.json
[21May2023 11:14:06.644] [main/INFO] [moonlight/]: Initialized color sets in 26ms
[21May2023 11:14:06.684] [main/INFO] [moonlight/]: Initialized color sets in 21ms
[21May2023 11:14:06.711] [main/INFO] [Framework/SYNCED_ENTITY_DATA]: Registered synced data key cgm:aiming for minecraft:player
[21May2023 11:14:06.711] [main/INFO] [Framework/SYNCED_ENTITY_DATA]: Registered synced data key cgm:shooting for minecraft:player
[21May2023 11:14:06.712] [main/INFO] [Framework/SYNCED_ENTITY_DATA]: Registered synced data key cgm:reloading for minecraft:player
[21May2023 11:14:06.775] [main/INFO] [supplementaries/]: Finished mod setup in: [0, 56, 1, 1, 0, 0, 0, 0, 0, 1] ms
[21May2023 11:14:06.806] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [moonlight] Found status: OUTDATED Current: 1.19.2-2.2.33 Target: 1.19.2-2.2.34
[21May2023 11:14:06.806] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [cgm] Starting version check at https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/cgm/update.json
[21May2023 11:14:06.842] [modloading-worker-0/INFO] [xaero.common.server.XaeroMinimapServer/]: Loading Xaero's Minimap - Stage 1/2 (Server)
[21May2023 11:14:06.844] [main/INFO] [xaero.common.server.XaeroMinimapServer/]: Loading Xaero's Minimap - Stage 2/2 (Server)
[21May2023 11:14:06.844] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [cgm] Found status: BETA Current: 1.3.4 Target: null
[21May2023 11:14:06.844] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [rsgauges] Starting version check at https://raw.githubusercontent.com/stfwi/rsgauges/versions/1.19.json
[21May2023 11:14:06.928] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [rsgauges] Found status: UP_TO_DATE Current: 1.2.18 Target: null
[21May2023 11:14:06.930] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [flywheel] Starting version check at https://api.modrinth.com/updates/flywheel/forge_updates.json
[21May2023 11:14:07.264] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [flywheel] Found status: UP_TO_DATE Current: 0.6.8.a Target: null
[21May2023 11:14:07.266] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [securitycraft] Starting version check at https://www.github.com/Geforce132/SecurityCraft/raw/master/Updates/Forge.json
[21May2023 11:14:07.817] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [securitycraft] Found status: UP_TO_DATE Current: 1.9.6.1 Target: null
[21May2023 11:14:07.819] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [mcwdoors] Starting version check at https://raw.githubusercontent.com/sketchmacaw/macawsmods/master/doors.json
[21May2023 11:14:07.859] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [mcwdoors] Found status: AHEAD Current: 1.0.9 Target: null
[21May2023 11:14:07.860] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [cfm] Starting version check at https://mrcrayfish.com/modupdatejson?id=cfm
[21May2023 11:14:08.309] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [cfm] Found status: BETA_OUTDATED Current: 7.0.0-pre34 Target: 7.0.0-pre35
[21May2023 11:14:08.310] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [framework] Starting version check at https://mrcrayfish.com/modupdatejson?id=framework
[21May2023 11:14:08.486] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [framework] Found status: BETA Current: 0.4.2 Target: 0.4.2
[21May2023 11:14:08.486] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[21May2023 11:14:08.880] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: AHEAD Current: 43.2.11 Target: null
[21May2023 11:14:08.881] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [supplementaries] Starting version check at https://raw.githubusercontent.com/MehVahdJukaar/Supplementaries/master/forge/update.json
[21May2023 11:14:08.920] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [supplementaries] Found status: OUTDATED Current: 1.19.2-2.3.10 Target: 1.19.2-2.3.11
[21May2023 11:14:10.307] [main/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21May2023 11:14:13.384] [main/WARN] [net.minecraft.server.packs.VanillaPackResources/]: Assets URL 'union:/C:/Users/me's%20Gaming%20PC/Documents/forge%201.19.2%20server/libraries/net/minecraft/server/1.19.2-20220805.130853/server-1.19.2-20220805.130853-srg.jar%23147!/assets/.mcassetsroot' uses unexpected schema
[21May2023 11:14:13.385] [main/WARN] [net.minecraft.server.packs.VanillaPackResources/]: Assets URL 'union:/C:/Users/me's%20Gaming%20PC/Documents/forge%201.19.2%20server/libraries/net/minecraft/server/1.19.2-20220805.130853/server-1.19.2-20220805.130853-srg.jar%23147!/data/.mcassetsroot' uses unexpected schema
[21May2023 11:14:13.631] [main/INFO] [supplementaries/]: Generated runtime SERVER_DATA for pack Supplementaries Generated Pack in: 101 ms
[21May2023 11:14:15.910] [main/INFO] [net.minecraft.world.item.crafting.RecipeManager/]: Skipping loading recipe supplementaries:inspirations/blackboard_clear as it's serializer returned null
[21May2023 11:14:15.921] [main/INFO] [net.minecraft.world.item.crafting.RecipeManager/]: Skipping loading recipe simpleplanes:plane_book as it's serializer returned null
[21May2023 11:14:15.939] [main/INFO] [net.minecraft.world.item.crafting.RecipeManager/]: Skipping loading recipe supplementaries:inspirations/flag_dye as it's serializer returned null
[21May2023 11:14:15.975] [main/INFO] [net.minecraft.world.item.crafting.RecipeManager/]: Skipping loading recipe supplementaries:inspirations/flag_clear as it's serializer returned null
[21May2023 11:14:16.016] [main/INFO] [net.minecraft.world.item.crafting.RecipeManager/]: Loaded 27 recipes
[21May2023 11:14:16.737] [main/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 3682 advancements
[21May2023 11:14:16.747] [main/INFO] [dan200.computercraft.shared.UpgradeManager/]: Loaded 9 turtle upgrades
[21May2023 11:14:16.748] [main/INFO] [dan200.computercraft.shared.UpgradeManager/]: Loaded 3 pocket computer upgrades
[21May2023 11:14:16.765] [main/INFO] [supplementaries/]: Loaded  8 flute songs
[21May2023 11:14:19.469] [main/INFO] [supplementaries/]: Finished additional setup in 37 ms
[21May2023 11:14:20.025] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Starting minecraft server version 1.19.2
[21May2023 11:14:20.027] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Loading properties
[21May2023 11:14:20.034] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Default game type: SURVIVAL
[21May2023 11:14:20.036] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Generating keypair
[21May2023 11:14:20.108] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Starting Minecraft server on *:25565
[21May2023 11:14:20.128] [Server thread/INFO] [net.minecraft.server.network.ServerConnectionListener/]: Using default channel type
[21May2023 11:14:20.594] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Preparing level "world"
[21May2023 11:14:20.990] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Preparing start region for dimension minecraft:overworld
[21May2023 11:14:25.752] [Worker-Main-2/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[21May2023 11:14:25.956] [Worker-Main-3/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[21May2023 11:14:26.257] [Worker-Main-2/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[21May2023 11:14:26.272] [Worker-Main-2/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[21May2023 11:14:26.275] [Worker-Main-2/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[21May2023 11:14:26.295] [Worker-Main-3/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[21May2023 11:14:26.297] [Worker-Main-2/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[21May2023 11:14:26.298] [Worker-Main-3/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[21May2023 11:14:26.299] [Worker-Main-3/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[21May2023 11:14:26.303] [Worker-Main-3/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[21May2023 11:14:26.307] [Worker-Main-3/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[21May2023 11:14:26.492] [Worker-Main-2/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[21May2023 11:14:26.947] [Server thread/WARN] [net.minecraft.network.syncher.SynchedEntityData/]: defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityPheasant from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
[21May2023 11:14:26.992] [Worker-Main-4/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 54%
[21May2023 11:14:27.174] [Server thread/WARN] [net.minecraft.network.syncher.SynchedEntityData/]: defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntitySongbird from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
[21May2023 11:14:27.276] [Server thread/WARN] [net.minecraft.network.syncher.SynchedEntityData/]: defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityBadger from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
[21May2023 11:14:27.359] [Server thread/WARN] [net.minecraft.network.syncher.SynchedEntityData/]: defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityTurkey from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
[21May2023 11:14:27.365] [Server thread/WARN] [net.minecraft.network.syncher.SynchedEntityData/]: defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityBoar from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
[21May2023 11:14:27.427] [Server thread/WARN] [net.minecraft.network.syncher.SynchedEntityData/]: defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityGoose from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
[21May2023 11:14:27.434] [Server thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Time elapsed: 6443 ms
[21May2023 11:14:27.435] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Done (7.090s)! For help, type "help"
[21May2023 11:14:27.463] [Server thread/INFO] [net.minecraftforge.server.permission.PermissionAPI/]: Successfully initialized permission handler forge:default_handler
[21May2023 11:14:27.473] [Server thread/INFO] [mtr.libraries.org.eclipse.jetty.server.Server/]: jetty-9.4.44.v20210927; built: 2021-09-27T23:02:44.612Z; git: 8da83308eeca865e495e53ef315a249d63ba9332; jvm 17.0.1+12-LTS-39
[21May2023 11:14:27.526] [Server thread/INFO] [mtr.libraries.org.eclipse.jetty.server.handler.ContextHandler/]: Started m.l.o.e.j.s.ServletContextHandler@6ca02975{/,union:/C:/Users/me's%20Gaming%20PC/Documents/forge%201.19.2%20server/mods/MTR-forge-1.19.2-3.1.6.jar%23139!/assets/mtr/website,AVAILABLE}
[21May2023 11:14:27.557] [Server thread/INFO] [mtr.libraries.org.eclipse.jetty.server.AbstractConnector/]: Started ServerConnector@632dffb0{HTTP/1.1, (http/1.1)}{0.0.0.0:8888}
[21May2023 11:14:27.558] [Server thread/INFO] [mtr.libraries.org.eclipse.jetty.server.Server/]: Started @47818ms
[21May2023 11:14:28.433] [Server thread/WARN] [net.minecraft.network.syncher.SynchedEntityData/]: defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityLammergeier from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
[21May2023 11:14:28.435] [Server thread/WARN] [net.minecraft.network.syncher.SynchedEntityData/]: defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityFeralWolf from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
[21May2023 16:22:36.949] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping the server
[21May2023 16:22:37.003] [Server thread/INFO] [mtr.libraries.org.eclipse.jetty.server.AbstractConnector/]: Stopped ServerConnector@632dffb0{HTTP/1.1, (http/1.1)}{0.0.0.0:8888}
[21May2023 16:22:37.006] [Server thread/INFO] [mtr.libraries.org.eclipse.jetty.server.handler.ContextHandler/]: Stopped m.l.o.e.j.s.ServletContextHandler@6ca02975{/,union:/C:/Users/Bennett's%20Gaming%20PC/Documents/forge%201.19.2%20server/mods/MTR-forge-1.19.2-3.1.6.jar%23139!/assets/mtr/website,STOPPED}
[21May2023 16:22:37.010] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[21May2023 16:22:37.011] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[21May2023 16:22:37.011] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[21May2023 16:22:37.854] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[21May2023 16:22:38.559] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[21May2023 16:22:38.561] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[21May2023 16:22:38.704] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (world): All chunks are saved
[21May2023 16:22:38.704] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[21May2023 16:22:38.706] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21May2023 16:22:38.708] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
