### ISSUE TITLE
Crash on turtle fuel consumption

### ISSUE THREAD

**Issue by delipunch** [SquidDev-CC/CC-Tweaked#316] opened 2019-11-25 05:57 UTC
https://pastebin.com/QGYF68ZR

Game crashes when a turtle starts to burn fuel to execute a moving command such as excavate.  Disabling the need for fuel fixes this problem.  Trying to execute say, excavate, with need_fuel on whilst no fuel is available, the execution stops with a need fuel error message, rather than a game crash.

CC:T version: 1.85.0
MC version: 1.14.4
Forge version: 1.14.4-28.1.0

**Comment by lupus590** [comment] 2019-11-25 06:20
Does the crash happen if the turtle has fuel in its inventory?

What happens when you do `turtle.refuel(0)` and `turtle.refuel(1)` with and without a valid fuel item in the currently selected slot?

**Comment by delipunch** [comment] 2019-11-25 06:52
I thought I was clear enough about fuel being in the turtle inventory. Guess not. Learn 2 english, me.
Yes, it crashes with fuel in the first slot of its inventory - the one with a square around it.
`turtle.refuel(0)` and `turtle.refuel(1)` both crash the game if there is fuel in slot 0, the slot with a square around it. If there isn't, the command returns
`false`
`No items to combust`

**Comment by SquidDev** [comment] 2019-11-25 08:52
This looks like another duplicate of #306. Please update to a version of Forge beyond 28.1.5. Sorry, I should have made that a hard dependency - that has been fixed for the next release.

**Closed by SquidDev** 2019-11-25 08:52 UTC
