### ISSUE TITLE
Ender modems range and cross dim messages feature changes

### ISSUE THREAD

**Issue by OHakimen** [SquidDev-CC/CC-Tweaked#1315] opened 2023-01-29 14:58 UTC
Ender modems currently have a infinite range and work cross dimension (ie .: nether to overworld and vise-versa).

The infinite range modens are nerfed by some devs in forks, my suggestion is to use config options for both the range and cross dimensional modem messages.

i think the default range could be something like 1024 blocks and using a -1 to denote infinite range, and a boolean flag that allows cross dimensional modem messages to be sent.

**Comment by Wojbie** [comment] 2023-01-29 18:02
Duplicate of: #955

**Comment by SquidDev** [comment] 2023-02-03 19:27
As Wojbie mentioned, there's a wider discussion on rebalancing ender modems in #955. For now, I don't think I really want to add a config option for it.

**Closed as not planned by SquidDev** 2023-02-03 19:27 UTC
Labels: enhancement, area-Minecraft
