### ISSUE TITLE
Turtle Miner breaks the game.

### ISSUE THREAD

**Issue by Mr-PASTER** [SquidDev-CC/CC-Tweaked#1808] opened 2024-04-26 13:09 UTC
### Minecraft Version

1.19.x

### Version

1.101.4

### Details

logs/ [crash-2024-04-26_16.02.29-client.txt](https://github.com/cc-tweaked/CC-Tweaked/files/15130967/crash-2024-04-26_16.02.29-client.txt)

The problem is that the simple turtles and computer blocks work, but the miner turtle is broken
https://youtu.be/tyGGKAPCaSE

**Comment by Mr-PASTER** [comment] 2024-04-26 13:12
I used only standard shaders, without additional add-ons

**Comment by SquidDev** [comment] 2024-04-26 13:20
Thanks for the report! This appears to be a duplicate of #1324, which is caused by Optifine not supporting the latest version of Forge. You'll either need to downgrade Forge ([the optifine downloads page has a list of the recommended version of Forge for each Optifine version](https://optifine.net/downloads)) or upgrade to an alternative shader mod like [Occulus](https://modrinth.com/mod/oculus).

**Closed as not planned by SquidDev** 2024-04-26 13:20 UTC
Labels: bug, duplicate, area-Minecraft
