### ISSUE TITLE
turtle.compare() crash

### ISSUE THREAD

**Issue by C4to** [SquidDev-CC/CC-Tweaked#205] opened 2019-05-12 14:08 UTC
Minecraft version: 1.12.2
CC:T version: 1.82.2

bug: Called the turtle.compare() function through the interactive lua terminal in an advanced mining  turtle, with spruces leaves in first slot selected and infront of the turtle, which induced a server crash.

**Comment by SquidDev** [comment] 2019-05-12 14:10
Duplicate of 179, should have been fixed in 1.82.3.

**Closed by SquidDev** 2019-05-12 14:10 UTC
