### ISSUE TITLE
turtle.craft()

### ISSUE THREAD

**Issue by gogedo** [SquidDev-CC/CC-Tweaked#1567] opened 2023-08-22 14:43 UTC
### Minecraft Version

1.20.x

### Version

cc-tweaked-1.20.1-forge-1.107.0

### Details

Turtle don't craft

**Comment by SirEdvin** [comment] 2023-08-22 14:49
Do you equip crafting table?

**Comment by SquidDev** [comment] 2023-08-23 09:24
I'm afraid I cannot reproduce this. Could you post a screenshot of your turtle's GUI, with the recipe and error message you get visible?

**Comment by SquidDev** [comment] 2023-08-31 20:42
Afraid I'm going to close this as the original report doesn't give me much to go on here. Happen to reopen if someone can reply with further information.

**Closed as not planned by SquidDev** 2023-08-31 20:42 UTC
Labels: bug, cannot reproduce, area-Minecraft
