### ISSUE TITLE
[1.13.2] Error Loading mod during Load_registries event phase Client Side

### ISSUE THREAD

**Issue by Morpheus1101** [SquidDev-CC/CC-Tweaked#116] opened 2019-02-15 22:48 UTC
## Useful information to include:
 - CC: Tweaked version 1.80pr1.14
[latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/2871119/latest.log)

 - Detailed reproduction steps!** Put mod in and attempt to load game

**Comment by SquidDev** [comment] 2019-02-15 22:59
Fun times, this is going to be one of those "runs perfectly in dev", but nowhere else issues. :) I'll have a fiddle.

**Comment by hugeblank** [comment] 2019-02-15 23:15
<img width="560" alt="screen shot 2019-02-15 at 3 13 31 pm 1" src="https://user-images.githubusercontent.com/16393543/52889362-64294f00-3134-11e9-91f1-7fd76ac343ac.png">
Is this relevant?

**Comment by Morpheus1101** [comment] 2019-02-15 23:23
I dont ever get that far, it dosent load on client to make a world to be able to look at anything, but it does error saying basically no textures were valid to load

**Comment by SquidDev** [comment] 2019-02-15 23:51
Are you running 1.13 with any other mods? I seem to remember seeing a similar Forge issue occurring when multiple mods were loaded, but can't find reference to it now.

**Comment by Morpheus1101** [comment] 2019-02-15 23:57
Yes i have multiple mods

**Comment by SquidDev** [comment] 2019-02-16 00:07
Yeah, this sadly looks like an instance of https://github.com/MinecraftForge/MinecraftForge/issues/5446, so we're waiting on a Forge fix. 

@hugeblank See https://github.com/MinecraftForge/MinecraftForge/issues/5470

**Comment by SquidDev** [comment] 2019-02-17 19:40
I believe both of these should be fixed in Forge now.

**Comment by Morpheus1101** [comment] 2019-02-19 00:27
Not sure if this is a case of the same issue just slightly different, but now it errors client side during the common_setup event phase

[latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/2877768/latest.log)

**Comment by SquidDev** [comment] 2019-02-19 10:44
That's an entirely different issue, but might as well track it here.

```
[10:22:29] [modloading-worker-15/ERROR]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class dan200.computercraft.shared.proxy.ComputerCraftProxyCommon init(Lnet/minecraftforge/fml/event/lifecycle/FMLCommonSetupEvent;)V
		2: ASM: class dan200.computercraft.shared.Config load(Lnet/minecraftforge/fml/event/lifecycle/FMLCommonSetupEvent;)V
java.lang.NullPointerException
	at cpw.mods.modlauncher.TransformerClassWriter.getCommonSuperClass(TransformerClassWriter.java:84)
	at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1209) ~[asm-6.2.jar:?]
	at org.objectweb.asm.Frame.merge(Frame.java:1293) ~[asm-6.2.jar:?]
	at org.objectweb.asm.Frame.merge(Frame.java:1191) ~[asm-6.2.jar:?]
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1604) ~[asm-6.2.jar:?]
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1540) ~[asm-6.2.jar:?]
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:807) ~[asm-tree-6.2.jar:?]
```

It looks like a bug in modlauncher, but looking at their code, I've no clue how that would happen. It may be worth trying to trying to remove some mods to see if there's another mod messing with things here.

**Comment by Morpheus1101** [comment] 2019-02-19 11:20
I'll take a run through after work tom as i h ave another mod that is also having issues with another mod in the list of all i have as well i need to track down.

**Comment by Morpheus1101** [comment] 2019-02-20 06:01
Ok, so after testing, i have come to the conclusion that i cant work it out and seems to be 1 of a handful of mods that seem to error, rmeove offending mod and re-add an it just seems to work again aok with the same mods back in you originally started with, so while this occurs and is reproducable around 1 a day, i cant pinpoint a specific mod/s that causing it.

**Comment by SquidDev** [comment] 2019-03-16 17:48
I've been unable to reproduce this. Given that CC:T is not a core mod, and this is happening while transforming classes, I suspect this is (or was) a bug in Forge or mod launcher.

**Closed by SquidDev** 2019-03-16 17:48 UTC
Labels: bug, invalid
