### ISSUE TITLE
Monitor extends weirdly?

### ISSUE THREAD

**Issue by AnexCanBeDestroyed** [SquidDev-CC/CC-Tweaked#1393] opened 2023-03-28 13:50 UTC
### Minecraft Version

1.19.x

### Version

1.19.2 1.101.2

### Details

I was doing some programming and this happened, i dont really know how to replicate it..
I am using no texture pack or other mods than the CC Tweaked Mod
Updating those Monitors or breaking them just makes them bug again when i replace them
![AnotherWha](https://user-images.githubusercontent.com/112589859/228257985-12f0e021-a252-4d69-9447-d6387278ed10.png)
![Wha](https://user-images.githubusercontent.com/112589859/228257434-28ab1923-cf43-4e00-9707-c786f4477c9a.png)

**Comment by SquidDev** [comment] 2023-03-29 17:36
Thank you for the report! I thought we'd squashed this bug, but apparently it's back again with a vengeance :/. Just a couple of questions:

 - Would you be able to upload the logs of the session when this occurred? In the past (https://github.com/cc-tweaked/CC-Tweaked/issues/879), this has been caused by some other error causing issues while monitors are mid-resize.

 - For the broken monitors, would you be able to open F3 mode and post the result of the ["Targeted monitor" section of the debug screen](https://user-images.githubusercontent.com/4346137/164968572-120dc2a5-84be-4c6e-980f-016a278e9f25.png). I'd expect the left most monitor to be `(0, 0), (6, 1)`, and then the x coordinate to increase for each, but just want to make sure.

 - > I dont really know how to replicate it [...] Updating those Monitors or breaking them just makes them bug again when i replace them

   This sounds like it's reproducible in this specific case, but not generally? Sorry, not quite sure what you mean here!

**Comment by SquidDev** [comment] 2023-06-02 18:40
I'm going to close this as I've been unable to reproduce this. If folks have more information, happy to reopen this again.

**Closed as not planned by SquidDev** 2023-06-02 18:40 UTC
Labels: bug, cannot reproduce, area-Minecraft
