### ISSUE TITLE
Monitor bug: TConstruct fluid tanks nearby un-render contents when monitor is placed while computer is running

### ISSUE THREAD

**Issue by fatboychummy** [SquidDev-CC/CC-Tweaked#1204] opened 2022-11-04 05:55 UTC
### Minecraft Version

1.16.x

### Version

1.101.0

### Details

Monitors are rendering about a pixel up and left of where they should be, they seem to also be making the rendered fluid in nearby Tinker tanks disappear.

Other tanks with fluids in it (non-tinkers) seem to cause the tinker tanks to render properly.

## Overall issue + pixel offset issue
https://user-images.githubusercontent.com/39929480/199897635-15f5a084-5fc1-457c-af47-0f27898bb816.mp4

## Testing issue + other mods' tanks
https://cdn.discordapp.com/attachments/477911902152949771/1037961268998443008/ding152.mp4 (video too large to upload to github)

## Test with just CC and TConstruct
![image](https://user-images.githubusercontent.com/39929480/199900054-f8777cd8-b158-4f76-b796-50ad514ed254.png)

There should be lava in the tanks in the above image. Pixel offset is interestingly not noticed here, there may be another mod interfering there. It's way too late currently for me to continue searching however, so for now I will just name the modpack I am running that is experiencing the offset: "Stacia Expert"

**Comment by fatboychummy** [comment] 2022-11-04 05:56
![image](https://user-images.githubusercontent.com/39929480/199900902-652e6591-3187-46c1-b8bd-c8e50d544993.png)


Renders correctly when computer is turned off.

**Comment by fatboychummy** [comment] 2022-11-04 06:04
Reported on Tinker's repository as well in case it is not on CC's end: SlimeKnights/TinkersConstruct#5017

**Comment by SquidDev** [comment] 2022-11-04 09:31
Tanks not showing up appears to be a TBO-only issue, so you can work around this by switching to the VBO renderer.

I thought I'd fixed the border issues way back in ba976f9a16c2a248d2fc1a4b7bc80ee9bf3a1d26, so interesting it's still showing up.

**Comment by SquidDev** [comment] 2022-11-04 10:07
It's also worth noting that things _appear_ (I haven't tested thoroughly) to reset across chunk boundaries: tanks will render fine as long as they're in different chunks. Not actually sure why this is, I didn't think BE rendering was batched in the same way that chunks are!

**Comment by KnightMiner** [comment] 2022-11-10 19:10
To be clear, what is it in CC that causes the tanks to stop rendering? Normally this type of bug is because the render state is not properly reset like expected before my code runs, is there something CC tweaked needs to reset?

**Comment by SquidDev** [comment] 2022-11-10 19:15
https://github.com/cc-tweaked/CC-Tweaked/blob/1d3ecb551d1a9393a263a01bd4d0e8b47ca8df48/src/main/java/dan200/computercraft/client/render/TileEntityMonitorRenderer.java#L164-L187

So this is the code in question. There's a lot going on here (we're using shaders for one), but I'm not aware of other it causing issues elsewhere so it's very odd. Unfortunately RenderDoc doesn't appear to work on 1.16.x (I guess due to it still using legacy OpenGL), so not sure quite what is going on in the render state.

**Comment by SquidDev** [comment] 2022-11-10 19:22
This is 100% a CC:T bug though, so feel free to close the issue on your end.

**Comment by KnightMiner** [comment] 2022-11-10 21:42
The one thing that makes fluids weird is they use a custom render type, I have seen similar issues with them being invisible on fabulous until I found the right setting that is not used on fast/fancy, could be another similar property that needs to be set.

**Comment by SquidDev** [comment] 2022-12-15 18:43
Sorry for the delay in looking at this. I can confirm that this works on 1.18.x.

I'm going to close this, as I'm slowing down maintenance of older versions, and I don't think it's critical.

**Closed as not planned by SquidDev** 2022-12-15 18:43 UTC
Labels: bug, wontfix, area-Minecraft
